/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Perpus;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author faridz
 */
public class profil extends javax.swing.JFrame {
    
    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jUname = new javax.swing.JLabel();
        unametx = new javax.swing.JTextField();
        jNim = new javax.swing.JLabel();
        nimtx = new javax.swing.JTextField();
        jNama = new javax.swing.JLabel();
        namatx = new javax.swing.JTextField();
        jUsia = new javax.swing.JLabel();
        umurtx = new javax.swing.JTextField();
        jJurusan = new javax.swing.JLabel();
        jurusantx = new javax.swing.JTextField();
        jAlamat = new javax.swing.JLabel();
        alamattx = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btncanc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jUname.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jUname.setForeground(new java.awt.Color(41, 50, 65));
        jUname.setText("Username");

        unametx.setForeground(new java.awt.Color(41, 50, 65));
        unametx.setEnabled(false);
        unametx.setPreferredSize(new java.awt.Dimension(450, 40));
        unametx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unametxActionPerformed(evt);
            }
        });

        jNim.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jNim.setForeground(new java.awt.Color(41, 50, 65));
        jNim.setText("NIM");

        nimtx.setForeground(new java.awt.Color(41, 50, 65));
        nimtx.setPreferredSize(new java.awt.Dimension(450, 40));

        jNama.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jNama.setForeground(new java.awt.Color(41, 50, 65));
        jNama.setText("Nama");

        namatx.setForeground(new java.awt.Color(41, 50, 65));
        namatx.setPreferredSize(new java.awt.Dimension(450, 40));

        jUsia.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jUsia.setForeground(new java.awt.Color(41, 50, 65));
        jUsia.setText("Usia");

        umurtx.setForeground(new java.awt.Color(41, 50, 65));
        umurtx.setPreferredSize(new java.awt.Dimension(450, 40));

        jJurusan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jJurusan.setForeground(new java.awt.Color(41, 50, 65));
        jJurusan.setText("Jurusan");

        jurusantx.setForeground(new java.awt.Color(41, 50, 65));
        jurusantx.setPreferredSize(new java.awt.Dimension(450, 40));

        jAlamat.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jAlamat.setForeground(new java.awt.Color(41, 50, 65));
        jAlamat.setText("Alamat");

        alamattx.setForeground(new java.awt.Color(41, 50, 65));
        alamattx.setPreferredSize(new java.awt.Dimension(450, 80));

        btn_edit.setBackground(new java.awt.Color(46, 196, 182));
        btn_edit.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setBorder(null);
        btn_edit.setLabel("Simpan");
        btn_edit.setPreferredSize(new java.awt.Dimension(450, 40));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAlamat)
                            .addComponent(jUname)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alamattx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(unametx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(umurtx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nimtx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jNim)
                                        .addComponent(jUsia))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jJurusan)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jurusantx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNama)
                                            .addComponent(namatx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jUname)
                .addGap(10, 10, 10)
                .addComponent(unametx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNama)
                    .addComponent(jNim))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimtx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namatx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jJurusan)
                    .addComponent(jUsia))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurtx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jurusantx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jAlamat)
                .addGap(10, 10, 10)
                .addComponent(alamattx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btncanc.setFont(new java.awt.Font("Montserrat Light", 0, 36)); // NOI18N
        btncanc.setText("<");
        btncanc.setBorder(null);
        btncanc.setBorderPainted(false);
        btncanc.setPreferredSize(new java.awt.Dimension(50, 50));
        btncanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 50, 65));
        jLabel2.setText("Edit Profile.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btncanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unametxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unametxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_unametxActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed

        String uname = unametx.getText();
        String nim = nimtx.getText();
        String nama = namatx.getText();
        String alamat = alamattx.getText();
        String umur = umurtx.getText();
        String jurusan = jurusantx.getText();

        try{
            Connection c = Koneksi.getKoneksi();
            String sql = "UPDATE biodata SET nim = ?, nama = ?, alamat = ?, umur =?, jurusan = ? WHERE username = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nim);
            p.setString(2, nama);
            p.setString(3, alamat);
            p.setString(4, umur);
            p.setString(5, jurusan);
            p.setString(6, uname);

            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Terubah");
        }catch(SQLException e){
            System.out.println("Update Error");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btncancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancActionPerformed
        Usermenu a = new Usermenu();
        this.dispose();

    }//GEN-LAST:event_btncancActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
        UIManager.setLookAndFeel( new FlatLightLaf() );
    }catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField alamattx;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btncanc;
    private javax.swing.JLabel jAlamat;
    private javax.swing.JLabel jJurusan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNama;
    private javax.swing.JLabel jNim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jUname;
    private javax.swing.JLabel jUsia;
    public static javax.swing.JTextField jurusantx;
    public static javax.swing.JTextField namatx;
    public static javax.swing.JTextField nimtx;
    public static javax.swing.JTextField umurtx;
    public static javax.swing.JTextField unametx;
    // End of variables declaration//GEN-END:variables
}
